---
title: "L03 Variable Selection"
subtitle: "Data Science 3 with R (STAT 301-3)"
author: "YOUR NAME"
pagetitle: "L03 YOUR NAME"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin 
---


::: {.callout-tip icon=false}

## Github Repo Link

To link to your github **repo**sitory, appropriately edit the example link below. Meaning replace `https://your-github-repo-url` with your github repo url. Suggest verifying the link works before submitting.

[https://your-github-repo-url](https://your-github-repo-url)

:::

## Overview

The goals of this lab are to (1) learn to implement variable selection techniques using models we have learned, (2) introduce DART VC as a Bayesian approach to variable selection, and (3) introduce a new model type: support vector machines.

## Exercise

We will be re-visiting the rideshare dataset used in L02 Initial Setup. Find the `rideshare` dataset^[Kaggle Uber & Lyft Dataset ([see website](https://www.kaggle.com/datasets/brllrb/uber-and-lyft-dataset-boston-ma))] in the `data/` directory. Take a moment to read the variable definitions in `rideshare_codebook.txt`.

::: {.callout-note icon="false"}
## Prediction goal

The objective is to predict the `price` of an Uber & Lyft rideshare.

:::

### Getting Started

The initial setup has been completed for you using the following settings:

- read in data, converted character variables to factors, removed missingness issues with the outcome variable `price`.
- transformed the target variable `price` with a log10 transformation
- downsampled the dataset to 0.5% of the original data stratified by `price_log10` for computation purposes
- implemented an 80-20 training-test split using stratified sampling (stratified by target variable with 4 strata)
- resamples were constructed by taking the training dataset and applying repeated V-fold cross-validation (5 folds, 3 repeat) with stratification on the target variable with 4 strata.

1. Run `1_initial_setup.R`. 
2. After running the script the `data-splitting/` directory should contain `rideshare_training.rda`, `rideshare_testing.rda`, and `rideshare_folds.rda`. 
3. Check to see if any of these should be added to the `.gitignore` file.

### Task 1

Use Lasso regression to perform variable selection. 

* Resample
  - use a V-fold cross validation^[Different from the folds created in the initial setup and is done to guard against overfitting.]: 5 folds, 1 repeat, & stratify on on target variable
  - `seed = 987`
* Recipe
  - remove `price, id, datetime, timezone, product_id`
  - other basic steps to form a minimal working recipe
* Model & Tuning
  - use the `glmnet` engine
  - tune the `penalty` on log 10 scale (the default) with range -3 to 0
  - use a regular grid of 5 with range 

After finalizing and fitting the optimal Lasso model, what variables were selected to include in your model?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE --- just need the list of selected variables

:::

### Task 2

Use Random Forest to perform variable selection. 

* Resample
  - use a V-fold cross validation^[Different from the folds created in the initial setup and is done to guard against overfitting.]: 5 folds, 1 repeat, & stratify on on target variable
  - `seed = 987`
* Recipe
  - remove `price, id, datetime, timezone, product_id`
  - other basic steps to form a minimal working recipe
* Model & Tuning
  - `ranger` engine
  - in the engine set `importance = "impurity"` --- this is what allows us to extract the variable importance
  - set `trees = 1000`
  - tune `mtry` and `min_n`
  - use a regular grid with `levels = 4`

After finalizing and fitting the optimal random forest model, select the top 20 important variables using `vip::vi()`. What variables were selected to include in your model?

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE --- just need the list of selected variables

:::

### Task 3

Use DART VC-measure (via the `bayesVC` package^[[GitHub repo](https://github.com/mattsheng/bayesVC) and [paper](https://arxiv.org/abs/2509.07121).]) to perform variable selection. Currently, DART VC-measure only supports regression problems, not classification problems.

- Install `bayesVC` package from GitHub: `pak::pkg_install("mattsheng/bayesVC")` 
- Read example usage of `DartVC()` in GitHub repo [mattsheng/bayesVC](https://github.com/mattsheng/bayesVC/tree/main?tab=readme-ov-file#example) 
  - Run `?bayesVC::DartVC` to read function help page
- Use `DartVC()` with `backend = "BART"`, `Lrep = 10`, and `seed = 987`
  * use the `seed` argument of the function instead of calling `set.seed()` before `DartVC()`
- `DartVC()` requires separate arguments for `y` and `X`
  - `prep()` and `bake()` your recipe in Task 2
  - Extract `price_log10`; this is your `y`. Make sure `y` is a vector, not a tibble
  - Extract all other columns but `price_log10`; this is your `X`. Make sure `X` is a matrix, not a tibble
- Resamples and tuning are **not needed**

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE --- just need the list of selected variables

:::

### Task 4

Now that variable selection/screening has been completed we can proceed to feature engineering (recipe building).

Create 3 recipes, one for each variable selection method from Tasks 1–3. Each recipe should contain the standard minimal steps to run a recipe such as dummy encoding, handling zero variance, normalization (if appropriate).

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE --- should provide display code of recipes

:::

### Task 5

Fit each of the recipes to the following models and record computation time:

1. Support vector machine (polynomial): tune `cost`, `degree`, and `scale_factor` (default values are sufficient, free to change if you want)

2.  Support vector machine (radial basis function): tune `cost` and `rbf_sigma` (default values a sufficient, free to change if you want)


Some general notes:

- A basic layout is suggested/provided in `4_tune_template.R`.
- We also want to collect how long it takes the tuning process for each model type. We can use the `tictoc` package --- code is provided in `4_tune_template.R`.
  * Runtime is **most accurate** when
    1. using background job
    2. only 1 script is running at a time
    3. no other apps are opened

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE --- should delete this box, the results in Tasks 6 & 7 should provide sufficient evidence this was completed

:::


### Task 6

Provide a nicely formatted table of model results. The table should include the model name, recipe name, best performance achieved, standard error of metric, and run time.

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE --- no code, only presentation of results

:::

### Task 7

Evaluate the best performing model on the testing data. This should include the interpretation of at least 2 metrics and a plot of observed vs predicted.

::: {.callout-tip icon="false"}
## Solution

YOUR SOLUTION HERE --- no code, only presentation of results

:::
